name: Update LiveKit SDK version

on:
  repository_dispatch:
    types: [update-livekit-version]
  workflow_dispatch:
    inputs:
      version:
        description: 'LiveKit SDK version'
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    name: Update LiveKit SDK
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update LiveKit Version
        run: ./ci/update_livekit_version.sh "${{ env.NEW_VERSION }}"

      - name: Generate changeset
        run: |
          cat > ".changeset/update-livekit-sdk.md" <<'EOF'
          ---
          "components-android": patch
          ---

          Update LiveKit SDK to ${{ env.NEW_VERSION }}
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CHANGESET_GH_TOKEN }}
          branch: update-livekit-sdk/${{ env.NEW_VERSION }}
          title: Update LiveKit SDK to ${{ env.NEW_VERSION }}
          commit-message: Update LiveKit SDK to ${{ env.NEW_VERSION }}
